---------------------------------------------------------------------------------------------------
-- File Revision $Rev: 37 $
-- Last change $Date: 2011-05-14 17:45:41 +0100 (Sat, 14 May 2011) $
-- SVN URL $HeadURL: https://orasash.svn.sourceforge.net/svnroot/orasash/v2.3/repo_5_waitgroups.sql $
---------------------------------------------------------------------------------------------------

-- (c) Kyle Hailey 2007
-- v2.0 List of events with classes


create table waitgroups (
 NAME         VARCHAR2(64),
 WAIT_CLASS   VARCHAR2(64)
);
create index waitgroups_i on waitgroups(name);

truncate table waitgroups;

insert into waitgroups values ('null event','Other');
insert into waitgroups values ('pmon timer','Idle');
insert into waitgroups values ('rdbms ipc message','Idle');
insert into waitgroups values ('kst: async disk IO','System I/O');
insert into waitgroups values ('ksfd: async disk IO','System I/O');
insert into waitgroups values ('Datapump dump file I/O','User I/O');
insert into waitgroups values ('dbms_file_transfer I/O','User I/O');
insert into waitgroups values ('DG Broker configuration file I/O','User I/O');
insert into waitgroups values ('Data file init write','User I/O');
insert into waitgroups values ('Log file init write','User I/O');
insert into waitgroups values ('Log archive I/O','System I/O');
--insert into waitgroups values ('RMAN backup & recovery I/O','System I/O');
insert into waitgroups values ('Standby redo I/O','System I/O');
insert into waitgroups values ('Backup: sbtinit','Administrative');
insert into waitgroups values ('Backup: sbtopen','Administrative');
insert into waitgroups values ('Backup: sbtread','Administrative');
insert into waitgroups values ('Backup: sbtwrite','Administrative');
insert into waitgroups values ('Backup: sbtclose','Administrative');
insert into waitgroups values ('Backup: sbtinfo','Administrative');
insert into waitgroups values ('Backup: sbtremove','Administrative');
insert into waitgroups values ('Backup: sbtbackup','Administrative');
insert into waitgroups values ('Backup: sbtclose2','Administrative');
insert into waitgroups values ('Backup: sbtcommand','Administrative');
insert into waitgroups values ('Backup: sbtend','Administrative');
insert into waitgroups values ('Backup: sbterror','Administrative');
insert into waitgroups values ('Backup: sbtinfo2','Administrative');
insert into waitgroups values ('Backup: sbtinit2','Administrative');
insert into waitgroups values ('Backup: sbtread2','Administrative');
insert into waitgroups values ('Backup: sbtremove2','Administrative');
insert into waitgroups values ('Backup: sbtrestore','Administrative');
insert into waitgroups values ('Backup: sbtwrite2','Administrative');
insert into waitgroups values ('Backup: sbtpcbackup','Administrative');
insert into waitgroups values ('Backup: sbtpccancel','Administrative');
insert into waitgroups values ('Backup: sbtpccommit','Administrative');
insert into waitgroups values ('Backup: sbtpcend','Administrative');
insert into waitgroups values ('Backup: sbtpcquerybackup','Administrative');
insert into waitgroups values ('Backup: sbtpcqueryrestore','Administrative');
insert into waitgroups values ('Backup: sbtpcrestore','Administrative');
insert into waitgroups values ('Backup: sbtpcstart','Administrative');
insert into waitgroups values ('Backup: sbtpcstatus','Administrative');
insert into waitgroups values ('Backup: sbtpcvalidate','Administrative');
insert into waitgroups values ('io done','System I/O');
insert into waitgroups values ('i/o slave wait','Idle');
insert into waitgroups values ('wait for unread message on broadcast channel','Idle');
insert into waitgroups values ('wait for unread message on multiple broadcast channels','Idle');
insert into waitgroups values ('class slave wait','Idle');
insert into waitgroups values ('KSV master wait','Idle');
insert into waitgroups values ('os thread startup','Concurrency');
insert into waitgroups values ('watchdog main loop','Idle');
insert into waitgroups values ('DIAG idle wait','Idle');
insert into waitgroups values ('ges remote message','Idle');
insert into waitgroups values ('gcs remote message','Idle');
insert into waitgroups values ('SGA: MMAN sleep for component shrink','Idle');
insert into waitgroups values ('retry contact SCN lock master','Cluster');
insert into waitgroups values ('control file sequential read','System I/O');
insert into waitgroups values ('control file single write','System I/O');
insert into waitgroups values ('control file parallel write','System I/O');
insert into waitgroups values ('enq: PW - flush prewarm buffers','Application');
insert into waitgroups values ('latch: cache buffers chains','Concurrency');
insert into waitgroups values ('free buffer waits','Configuration');
insert into waitgroups values ('local write wait','User I/O');
insert into waitgroups values ('checkpoint completed','Configuration');
insert into waitgroups values ('write complete waits','Configuration');
insert into waitgroups values ('buffer read retry','User I/O');
insert into waitgroups values ('buffer busy waits','Concurrency');
insert into waitgroups values ('gc buffer busy','Cluster');
insert into waitgroups values ('read by other session','User I/O');
insert into waitgroups values ('multiple dbwriter suspend/resume for file offline','Administrative')
;

insert into waitgroups values ('buffer pool resize','Administrative');
insert into waitgroups values ('recovery read','System I/O');
insert into waitgroups values ('pi renounce write complete','Cluster');
insert into waitgroups values ('enq: RO - contention','Application');
insert into waitgroups values ('enq: RO - fast object reuse','Application');
insert into waitgroups values ('enq: KO - fast object checkpoint','Application');
insert into waitgroups values ('ARCH wait for pending I/Os','System I/O');
insert into waitgroups values ('ARCH wait for netserver start','Network');
insert into waitgroups values ('ARCH wait for netserver init 1','Network');
insert into waitgroups values ('ARCH wait for netserver init 2','Network');
insert into waitgroups values ('ARCH wait for flow-control','Network');
insert into waitgroups values ('ARCH wait for netserver detach','Network');
insert into waitgroups values ('ARCH wait for net re-connect','Network');
insert into waitgroups values ('LNS ASYNC control file txn','System I/O');
insert into waitgroups values ('LNS ASYNC archive log','Idle');
insert into waitgroups values ('LNS ASYNC dest activation','Idle');
insert into waitgroups values ('LNS ASYNC end of log','Idle');
insert into waitgroups values ('LNS wait on ATTACH','Network');
insert into waitgroups values ('LNS wait on SENDREQ','Network');
insert into waitgroups values ('LNS wait on DETACH','Network');
insert into waitgroups values ('LNS wait on LGWR','Network');
insert into waitgroups values ('LGWR wait on ATTACH','Network');
insert into waitgroups values ('LGWR wait on SENDREQ','Network');
insert into waitgroups values ('LGWR wait on DETACH','Network');
insert into waitgroups values ('LGWR sequential i/o','System I/O');
insert into waitgroups values ('LGWR random i/o','System I/O');
insert into waitgroups values ('LGWR wait on LNS','Network');
insert into waitgroups values ('RFS sequential i/o','System I/O');
insert into waitgroups values ('RFS random i/o','System I/O');
insert into waitgroups values ('RFS write','System I/O');
insert into waitgroups values ('ARCH wait on ATTACH','Network');
insert into waitgroups values ('ARCH wait on SENDREQ','Network');
insert into waitgroups values ('ARCH wait on DETACH','Network');
insert into waitgroups values ('ARCH sequential i/o','System I/O');
insert into waitgroups values ('ARCH random i/o','System I/O');
insert into waitgroups values ('log file sequential read','System I/O');
insert into waitgroups values ('log file single write','System I/O');
insert into waitgroups values ('log file parallel write','System I/O');
insert into waitgroups values ('latch: redo writing','Configuration');
insert into waitgroups values ('latch: redo copy','Configuration');
insert into waitgroups values ('log buffer space','Configuration');
insert into waitgroups values ('log file switch (checkpoint incomplete)','Configuration');
insert into waitgroups values ('log file switch (private strand flush incomplete)','Configuration');
insert into waitgroups values ('log file switch (archiving needed)','Configuration');
insert into waitgroups values ('switch logfile command','Administrative');
insert into waitgroups values ('log file switch completion','Configuration');
insert into waitgroups values ('log file sync','Commit');
insert into waitgroups values ('db file sequential read','User I/O');
insert into waitgroups values ('db file scattered read','User I/O');
insert into waitgroups values ('db file single write','User I/O');
insert into waitgroups values ('db file parallel write','System I/O');
insert into waitgroups values ('db file parallel read','User I/O');
insert into waitgroups values ('gc current request','Cluster');
insert into waitgroups values ('gc cr request','Cluster');
insert into waitgroups values ('gc cr disk request','Cluster');
insert into waitgroups values ('gc cr multi block request','Cluster');
insert into waitgroups values ('gc current multi block request','Cluster');
insert into waitgroups values ('gc block recovery request','Cluster');
insert into waitgroups values ('gc cr block 2-way','Cluster');
insert into waitgroups values ('gc cr block 3-way','Cluster');
insert into waitgroups values ('gc cr block busy','Cluster');
insert into waitgroups values ('gc cr block congested','Cluster');
insert into waitgroups values ('gc cr failure','Cluster');
insert into waitgroups values ('gc cr block lost','Cluster');
insert into waitgroups values ('gc cr block unknown','Cluster');
insert into waitgroups values ('gc current block 2-way','Cluster');
insert into waitgroups values ('gc current block 3-way','Cluster');
insert into waitgroups values ('gc current block busy','Cluster');
insert into waitgroups values ('gc current block congested','Cluster');
insert into waitgroups values ('gc current retry','Cluster');
insert into waitgroups values ('gc current block lost','Cluster');
insert into waitgroups values ('gc current split','Cluster');
insert into waitgroups values ('gc current block unknown','Cluster');
insert into waitgroups values ('gc cr grant 2-way','Cluster');
insert into waitgroups values ('gc cr grant busy','Cluster');
insert into waitgroups values ('gc cr grant congested','Cluster');
insert into waitgroups values ('gc cr grant unknown','Cluster');
insert into waitgroups values ('gc cr disk read','Cluster');
insert into waitgroups values ('gc current grant 2-way','Cluster');
insert into waitgroups values ('gc current grant busy','Cluster');
insert into waitgroups values ('gc current grant congested','Cluster');
insert into waitgroups values ('gc current grant unknown','Cluster');
insert into waitgroups values ('gc freelist','Cluster');
insert into waitgroups values ('gc prepare','Cluster');
insert into waitgroups values ('gc remaster','Cluster');
insert into waitgroups values ('gc current cancel','Cluster');
insert into waitgroups values ('gc cr cancel','Cluster');
insert into waitgroups values ('gc assume','Cluster');
insert into waitgroups values ('gc domain validation','Cluster');
insert into waitgroups values ('gc recovery free','Cluster');
insert into waitgroups values ('gc recovery quiesce','Cluster');
insert into waitgroups values ('gc claim','Cluster');
insert into waitgroups values ('gc quiesce wait','Cluster');
insert into waitgroups values ('direct path read','User I/O');
insert into waitgroups values ('direct path read temp','User I/O');
insert into waitgroups values ('direct path write','User I/O');
insert into waitgroups values ('direct path write temp','User I/O');
insert into waitgroups values ('PX Deq: Par Recov Reply','Idle');
insert into waitgroups values ('PX Deq: Par Recov Execute','Idle');
insert into waitgroups values ('PX Deq: Par Recov Change Vector','Idle');
insert into waitgroups values ('LogMiner: slave waiting for activate message','Idle');
insert into waitgroups values ('LogMiner: wakeup event for builder','Idle');
insert into waitgroups values ('LogMiner: wakeup event for preparer','Idle');
insert into waitgroups values ('LogMiner: wakeup event for reader','Idle');
insert into waitgroups values ('LogMiner: client waiting for transaction','Idle');
insert into waitgroups values ('wait for possible quiesce finish','Administrative');
insert into waitgroups values ('parallel recovery coordinator waits for cleanup of slaves','Idle');
insert into waitgroups values ('enq: TM - contention','Application');
insert into waitgroups values ('enq: ST - contention','Configuration');
insert into waitgroups values ('enq: HW - contention','Configuration');
insert into waitgroups values ('enq: SS - contention','Configuration');
insert into waitgroups values ('undo segment extension','Configuration');
insert into waitgroups values ('undo segment tx slot','Configuration');
insert into waitgroups values ('switch undo - offline','Administrative');
insert into waitgroups values ('alter rbs offline','Administrative');
insert into waitgroups values ('enq: TX - row lock contention','Application');
insert into waitgroups values ('enq: TX - allocate ITL entry','Configuration');
insert into waitgroups values ('enq: TX - index contention','Concurrency');
insert into waitgroups values ('enq: TW - contention','Administrative');
insert into waitgroups values ('sort segment request','Configuration');
insert into waitgroups values ('smon timer','Idle');
insert into waitgroups values ('PX Deq: Txn Recovery Start','Idle');
insert into waitgroups values ('PX Deq: Txn Recovery Reply','Idle');
insert into waitgroups values ('latch: Undo Hint Latch','Concurrency');
insert into waitgroups values ('statement suspended, wait error to be cleared','Configuration');
insert into waitgroups values ('latch: In memory undo latch','Concurrency');
insert into waitgroups values ('latch: MQL Tracking Latch','Concurrency');
insert into waitgroups values ('enq: SQ - contention','Configuration');
insert into waitgroups values ('PX Deq: Index Merge Reply','Idle');
insert into waitgroups values ('PX Deq: Index Merge Execute','Idle');
insert into waitgroups values ('PX Deq: Index Merge Close','Idle');
insert into waitgroups values ('PX Deq: kdcph_mai','Idle');
insert into waitgroups values ('PX Deq: kdcphc_ack','Idle');
insert into waitgroups values ('index (re)build online start','Administrative');
insert into waitgroups values ('index (re)build online cleanup','Administrative');
insert into waitgroups values ('index (re)build online merge','Administrative');
insert into waitgroups values ('latch: row cache objects','Concurrency');
insert into waitgroups values ('row cache lock','Concurrency');
insert into waitgroups values ('row cache read','Concurrency');
insert into waitgroups values ('cursor: mutex X','Concurrency');
insert into waitgroups values ('cursor: mutex S','Concurrency');
insert into waitgroups values ('cursor: pin S wait on X','Concurrency');
insert into waitgroups values ('latch: shared pool','Concurrency');
insert into waitgroups values ('latch: library cache','Concurrency');
insert into waitgroups values ('latch: library cache lock','Concurrency');
insert into waitgroups values ('latch: library cache pin','Concurrency');
insert into waitgroups values ('library cache pin','Concurrency');
insert into waitgroups values ('library cache lock','Concurrency');
insert into waitgroups values ('library cache load lock','Concurrency');
insert into waitgroups values ('BFILE read','User I/O');
insert into waitgroups values ('resmgr:cpu quantum','Scheduler');
insert into waitgroups values ('resmgr:internal state change','Concurrency');
insert into waitgroups values ('resmgr:internal state cleanup','Concurrency');
insert into waitgroups values ('resmgr:sessions to exit','Concurrency');
insert into waitgroups values ('resmgr:become active','Scheduler');
insert into waitgroups values ('TCP Socket (KGAS)','Network');
insert into waitgroups values ('alter system set dispatcher','Administrative');
insert into waitgroups values ('virtual circuit status','Idle');
insert into waitgroups values ('dispatcher timer','Idle');
insert into waitgroups values ('dispatcher listen timer','Network');
insert into waitgroups values ('dedicated server timer','Network');
insert into waitgroups values ('jobq slave wait','Idle');
insert into waitgroups values ('Wait for Table Lock','Application');
insert into waitgroups values ('pipe get','Idle');
insert into waitgroups values ('pipe put','Concurrency');
insert into waitgroups values ('enq: DB - contention','Administrative');
insert into waitgroups values ('PX Deque wait','Idle');
insert into waitgroups values ('PX Idle Wait','Idle');
insert into waitgroups values ('PX Deq: Join ACK','Idle');
insert into waitgroups values ('PX Deq Credit: need buffer','Idle');
insert into waitgroups values ('PX Deq: Msg Fragment','Idle');
insert into waitgroups values ('PX Deq: Parse Reply','Idle');
insert into waitgroups values ('PX Deq: Execute Reply','Idle');
insert into waitgroups values ('PX Deq: Execution Msg','Idle');
insert into waitgroups values ('PX Deq: Table Q Normal','Idle');
insert into waitgroups values ('PX Deq: Table Q Sample','Idle');
insert into waitgroups values ('Streams fetch slave: waiting for txns','Idle');
insert into waitgroups values ('Streams capture: filter callback waiting for ruleset','Application')
;

insert into waitgroups values ('Streams: RAC waiting for inter instance ack','Cluster');
insert into waitgroups values ('Streams: apply reader waiting for DDL to apply','Application');
insert into waitgroups values ('Streams capture: waiting for subscribers to catch up','Configuration
');

insert into waitgroups values ('Streams capture: resolve low memory condition','Configuration');
insert into waitgroups values ('enq: ZG - contention','Administrative');
insert into waitgroups values ('single-task message','Idle');
insert into waitgroups values ('SQL*Net message to client','Network');
insert into waitgroups values ('SQL*Net message to dblink','Network');
insert into waitgroups values ('SQL*Net more data to client','Network');
insert into waitgroups values ('SQL*Net more data to dblink','Network');
insert into waitgroups values ('SQL*Net message from client','Idle');
insert into waitgroups values ('SQL*Net more data from client','Network');
insert into waitgroups values ('SQL*Net message from dblink','Idle');
insert into waitgroups values ('SQL*Net more data from dblink','Network');
insert into waitgroups values ('SQL*Net break/reset to client','Application');
insert into waitgroups values ('SQL*Net break/reset to dblink','Application');
insert into waitgroups values ('PL/SQL lock timer','Idle');
insert into waitgroups values ('enq: UL - contention','Application');
insert into waitgroups values ('wait for EMON to process ntfns','Configuration');
insert into waitgroups values ('EMON idle wait','Idle');
insert into waitgroups values ('Streams AQ: waiting for messages in the queue','Idle');
insert into waitgroups values ('Streams AQ: waiting for time management or cleanup tasks','Idle');
insert into waitgroups values ('Streams AQ: enqueue blocked on low memory','Configuration');
insert into waitgroups values ('Streams AQ: delete acknowledged messages','Idle');
insert into waitgroups values ('Streams AQ: deallocate messages from Streams Pool','Idle');
insert into waitgroups values ('Streams AQ: qmn coordinator idle wait','Idle');
insert into waitgroups values ('Streams AQ: qmn slave idle wait','Idle');
insert into waitgroups values ('Streams AQ: RAC qmn coordinator idle wait','Idle');
insert into waitgroups values ('HS message to agent','Idle');
insert into waitgroups values ('ASM COD rollback operation completion','Administrative');
insert into waitgroups values ('kfk: async disk IO','System I/O');
insert into waitgroups values ('ASM background timer','Idle');
insert into waitgroups values ('ASM mount : wait for heartbeat','Administrative');
insert into waitgroups values ('ASM PST query : wait for [PM][grp][0] grant','Cluster');
insert into waitgroups values ('lock remastering','Cluster');
insert into waitgroups values ('JS kgl get object wait','Administrative');
insert into waitgroups values ('JS external job','Idle');
insert into waitgroups values ('JS kill job wait','Administrative');
insert into waitgroups values ('JS coord start wait','Administrative');
insert into waitgroups values ('events in waitclass Other','Other');
insert into waitgroups values ('unspecified wait event','Other');
insert into waitgroups values ('latch activity','Other');
insert into waitgroups values ('wait list latch activity','Other');
insert into waitgroups values ('latch free','Other');
insert into waitgroups values ('wait list latch free','Other');
insert into waitgroups values ('ksqded','Other');
insert into waitgroups values ('global enqueue expand wait','Other');
insert into waitgroups values ('enq: KM - contention','Other');
insert into waitgroups values ('enq: KT - contention','Other');
insert into waitgroups values ('free process state object','Other');
insert into waitgroups values ('inactive session','Other');
insert into waitgroups values ('process terminate','Other');
insert into waitgroups values ('latch: session allocation','Other');
insert into waitgroups values ('check CPU wait times','Other');
insert into waitgroups values ('enq: CI - contention','Other');
insert into waitgroups values ('enq: PR - contention','Other');
insert into waitgroups values ('ksim generic wait event','Other');
insert into waitgroups values ('debugger command','Other');
insert into waitgroups values ('ksdxexeother','Other');
insert into waitgroups values ('ksdxexeotherwait','Other');
insert into waitgroups values ('enq: PE - contention','Other');
insert into waitgroups values ('enq: PG - contention','Other');
insert into waitgroups values ('ksbsrv','Other');
insert into waitgroups values ('ksbcic','Other');
insert into waitgroups values ('process startup','Other');
insert into waitgroups values ('process shutdown','Other');
insert into waitgroups values ('prior spawner clean up','Other');
insert into waitgroups values ('latch: messages','Other');
insert into waitgroups values ('rdbms ipc message block','Other');
insert into waitgroups values ('rdbms ipc reply','Other');
insert into waitgroups values ('latch: enqueue hash chains','Other');
insert into waitgroups values ('enq: FP - global fob contention','Other');
insert into waitgroups values ('imm op','Other');
insert into waitgroups values ('slave exit','Other');
insert into waitgroups values ('reliable message','Other');
insert into waitgroups values ('master exit','Other');
insert into waitgroups values ('ksv slave avail wait','Other');
insert into waitgroups values ('enq: PV - syncstart','Other');
insert into waitgroups values ('enq: PV - syncshut','Other');
insert into waitgroups values ('IPC send completion sync','Other');
insert into waitgroups values ('IPC wait for name service busy','Other');
insert into waitgroups values ('IPC busy async request','Other');
insert into waitgroups values ('IPC waiting for OSD resources','Other');
insert into waitgroups values ('ksxr poll remote instances','Other');
insert into waitgroups values ('ksxr wait for mount shared','Other');
insert into waitgroups values ('DBMS_LDAP: LDAP operation ','Other');
insert into waitgroups values ('wait for FMON to come up','Other');
insert into waitgroups values ('enq: FM - contention','Other');
insert into waitgroups values ('enq: XY - contention','Other');
insert into waitgroups values ('set director factor wait','Other');
insert into waitgroups values ('enq: AS - service activation','Other');
insert into waitgroups values ('enq: AS - modify service','Other');
insert into waitgroups values ('enq: PD - contention','Other');
insert into waitgroups values ('cleanup of aborted process','Other');
insert into waitgroups values ('enq: RU - contention','Other');
insert into waitgroups values ('enq: RU - waiting','Other');
insert into waitgroups values ('rolling migration: cluster quiesce','Other');
insert into waitgroups values ('LMON global data update','Other');
insert into waitgroups values ('latch: ges resource hash list','Other');
insert into waitgroups values ('DFS lock handle','Other');
insert into waitgroups values ('ges LMD to shutdown','Other');
insert into waitgroups values ('ges global resource directory to be frozen','Other');
insert into waitgroups values ('ges resource directory to be unfrozen','Other');
insert into waitgroups values ('gcs resource directory to be unfrozen','Other');
insert into waitgroups values ('ges LMD to inherit communication channels','Other');
insert into waitgroups values ('ges wait for lmon to be ready','Other');
insert into waitgroups values ('ges cgs registration','Other');
insert into waitgroups values ('wait for master scn','Other');
insert into waitgroups values ('ges reconfiguration to start','Other');
insert into waitgroups values ('ges2 proc latch in rm latch get 1','Other');
insert into waitgroups values ('ges2 proc latch in rm latch get 2','Other');
insert into waitgroups values ('ges lmd/lmses to freeze in rcfg - mrcvr','Other');
insert into waitgroups values ('ges lmd/lmses to unfreeze in rcfg - mrcvr','Other');
insert into waitgroups values ('ges LMON to join CGS group','Other');
insert into waitgroups values ('ges pmon to exit','Other');
insert into waitgroups values ('ges lmd and pmon to attach','Other');
insert into waitgroups values ('gcs drm freeze begin','Other');
insert into waitgroups values ('gcs remastering wait for write latch','Other');
insert into waitgroups values ('gcs remastering wait for read latch','Other');
insert into waitgroups values ('ges cached resource cleanup','Other');
insert into waitgroups values ('ges generic event','Other');
insert into waitgroups values ('ges retry query node','Other');
insert into waitgroups values ('ges process with outstanding i/o','Other');
insert into waitgroups values ('ges user error','Other');
insert into waitgroups values ('ges enter server mode','Other');
insert into waitgroups values ('gcs enter server mode','Other');
insert into waitgroups values ('gcs drm freeze in enter server mode','Other');
insert into waitgroups values ('gcs ddet enter server mode','Other');
insert into waitgroups values ('ges cancel','Other');
insert into waitgroups values ('ges resource cleanout during enqueue open','Other');
insert into waitgroups values ('ges resource cleanout during enqueue open-cvt','Other');
insert into waitgroups values ('ges master to get established for SCN op','Other');
insert into waitgroups values ('ges LMON to get to FTDONE ','Other');
insert into waitgroups values ('ges1 LMON to wake up LMD - mrcvr','Other');
insert into waitgroups values ('ges2 LMON to wake up LMD - mrcvr','Other');
insert into waitgroups values ('ges2 LMON to wake up lms - mrcvr 2','Other');
insert into waitgroups values ('ges2 LMON to wake up lms - mrcvr 3','Other');
insert into waitgroups values ('ges inquiry response','Other');
insert into waitgroups values ('ges reusing os pid','Other');
insert into waitgroups values ('ges LMON for send queues','Other');
insert into waitgroups values ('ges LMD suspend for testing event','Other');
insert into waitgroups values ('ges performance test completion','Other');
insert into waitgroups values ('kjbopen wait for recovery domain attach','Other');
insert into waitgroups values ('kjudomatt wait for recovery domain attach','Other');
insert into waitgroups values ('kjudomdet wait for recovery domain detach','Other');
insert into waitgroups values ('kjbdomalc allocate recovery domain - retry','Other');
insert into waitgroups values ('kjbdrmcvtq lmon drm quiesce: ping completion','Other');
insert into waitgroups values ('KJC: Wait for msg sends to complete','Other');
insert into waitgroups values ('kjctssqmg: quick message send wait','Other');
insert into waitgroups values ('kjctcisnd: Queue/Send client message','Other');
insert into waitgroups values ('gcs domain validation','Other');
insert into waitgroups values ('latch: gcs resource hash','Other');
insert into waitgroups values ('affinity expansion in replay','Other');
insert into waitgroups values ('wait for sync ack','Other');
insert into waitgroups values ('wait for verification ack','Other');
insert into waitgroups values ('wait for assert messages to be sent','Other');
insert into waitgroups values ('wait for scn ack','Other');
insert into waitgroups values ('lms flush message acks','Other');
insert into waitgroups values ('name-service call wait','Other');
insert into waitgroups values ('CGS wait for IPC msg','Other');
insert into waitgroups values ('kjxgrtest','Other');
insert into waitgroups values ('wait for tmc2 to complete','Other');
insert into waitgroups values ('wait for votes','Other');
insert into waitgroups values ('wait for rr lock release','Other');
insert into waitgroups values ('wait for message ack','Other');
insert into waitgroups values ('wait for record update','Other');
insert into waitgroups values ('wait for membership synchronization','Other');
insert into waitgroups values ('wait for split-brain resolution','Other');
insert into waitgroups values ('CGS skgxn join retry','Other');
insert into waitgroups values ('gcs to be enabled','Other');
insert into waitgroups values ('gcs log flush sync','Other');
insert into waitgroups values ('SGA: allocation forcing component growth','Other');
insert into waitgroups values ('SGA: sga_target resize','Other');
insert into waitgroups values ('control file heartbeat','Other');
insert into waitgroups values ('control file diagnostic dump','Other');
insert into waitgroups values ('enq: CF - contention','Other');
insert into waitgroups values ('enq: SW - contention','Other');
insert into waitgroups values ('enq: DS - contention','Other');
insert into waitgroups values ('enq: TC - contention','Other');
insert into waitgroups values ('enq: TC - contention2','Other');
insert into waitgroups values ('buffer exterminate','Other');
insert into waitgroups values ('buffer resize','Other');
insert into waitgroups values ('latch: cache buffers lru chain','Other');
insert into waitgroups values ('enq: PW - perwarm status in dbw0','Other');
insert into waitgroups values ('latch: checkpoint queue latch','Other');
insert into waitgroups values ('latch: cache buffer handles','Other');
insert into waitgroups values ('kcbzps','Other');
insert into waitgroups values ('buffer deadlock','Other');
insert into waitgroups values ('buffer latch','Other');
insert into waitgroups values ('cr request retry','Other');
insert into waitgroups values ('writes stopped by instance recovery or database suspension','Other')
;

insert into waitgroups values ('lock escalate retry','Other');
insert into waitgroups values ('lock deadlock retry','Other');
insert into waitgroups values ('prewarm transfer retry','Other');
insert into waitgroups values ('wait for MTTR advisory state object','Other');
insert into waitgroups values ('latch: object queue header operation','Other');
insert into waitgroups values ('latch: object queue header heap','Other');
insert into waitgroups values ('enq: WR - contention','Other');
insert into waitgroups values ('log switch/archive','Other');
insert into waitgroups values ('ARCH wait on c/f tx acquire 1','Other');
insert into waitgroups values ('ARCH wait on c/f tx acquire 2','Other');
insert into waitgroups values ('ARCH wait for process start 1','Other');
insert into waitgroups values ('ARCH wait for process death 1','Other');
insert into waitgroups values ('ARCH wait for process start 2','Other');
insert into waitgroups values ('ARCH wait for process death 2','Other');
insert into waitgroups values ('ARCH wait for process start 3','Other');
insert into waitgroups values ('ARCH wait for process death 3','Other');
insert into waitgroups values ('ARCH wait for process start 4','Other');
insert into waitgroups values ('ARCH wait for process death 4','Other');
insert into waitgroups values ('ARCH wait for process death 5','Other');
insert into waitgroups values ('ARCH wait for archivelog lock','Other');
insert into waitgroups values ('Wait on stby instance close','Other');
insert into waitgroups values ('RFS dispatch','Other');
insert into waitgroups values ('RFS attach','Other');
insert into waitgroups values ('RFS create','Other');
insert into waitgroups values ('RFS close','Other');
insert into waitgroups values ('RFS announce','Other');
insert into waitgroups values ('RFS register','Other');
insert into waitgroups values ('RFS detach','Other');
insert into waitgroups values ('RFS ping','Other');
insert into waitgroups values ('LGWR simulation latency wait','Other');
insert into waitgroups values ('LGWR-LNS wait on channel','Other');
insert into waitgroups values ('LGWR wait on full LNS buffer','Other');
insert into waitgroups values ('LNS simulation latency wait','Other');
insert into waitgroups values ('kcrrrcp','Other');
insert into waitgroups values ('LNS wait for LGWR redo','Other');
insert into waitgroups values ('Data Guard: process exit','Other');
insert into waitgroups values ('Data Guard: process clean up','Other');
insert into waitgroups values ('MRP wait on process start','Other');
insert into waitgroups values ('MRP wait on process restart','Other');
insert into waitgroups values ('MRP wait on startup clear','Other');
insert into waitgroups values ('MRP wait on process death','Other');
insert into waitgroups values ('MRP wait on state change','Other');
insert into waitgroups values ('MRP wait on state n_a','Other');
insert into waitgroups values ('MRP wait on state reset','Other');
insert into waitgroups values ('MRP wait on archivelog delay','Other');
insert into waitgroups values ('MRP wait on archivelog arrival','Other');
insert into waitgroups values ('MRP wait on archivelog archival','Other');
insert into waitgroups values ('FAL archive wait 1 sec for REOPEN minimum','Other');
insert into waitgroups values ('LGWR wait for redo copy','Other');
insert into waitgroups values ('latch: redo allocation','Other');
insert into waitgroups values ('log file switch (clearing log file)','Other');
insert into waitgroups values ('simulated log write delay','Other');
insert into waitgroups values ('enq: WL - contention','Other');
insert into waitgroups values ('enq: RN - contention','Other');
insert into waitgroups values ('DFS db file lock','Other');
insert into waitgroups values ('enq: DF - contention','Other');
insert into waitgroups values ('enq: IS - contention','Other');
insert into waitgroups values ('enq: FS - contention','Other');
insert into waitgroups values ('enq: DM - contention','Other');
insert into waitgroups values ('enq: RP - contention','Other');
insert into waitgroups values ('latch: KCL gc element parent latch','Other');
insert into waitgroups values ('enq: RT - contention','Other');
insert into waitgroups values ('enq: KK - context','Other');
insert into waitgroups values ('enq: IR - contention','Other');
insert into waitgroups values ('enq: IR - contention2','Other');
insert into waitgroups values ('enq: MR - contention','Other');
insert into waitgroups values ('enq: BR - file shrink','Other');
insert into waitgroups values ('enq: BR - proxy-copy','Other');
insert into waitgroups values ('enq: ID - contention','Other');
insert into waitgroups values ('enq: MN - contention','Other');
insert into waitgroups values ('enq: PL - contention','Other');
insert into waitgroups values ('Logical Standby Apply shutdown','Other');
insert into waitgroups values ('Logical Standby pin transaction','Other');
insert into waitgroups values ('Logical Standby dictionary build','Other');
insert into waitgroups values ('Logical Standby Terminal Apply','Other');
insert into waitgroups values ('enq: SB - contention','Other');
insert into waitgroups values ('enq: XR - quiesce database','Other');
insert into waitgroups values ('enq: XR - database force logging','Other');
insert into waitgroups values ('change tracking file synchronous read','Other');
insert into waitgroups values ('change tracking file synchronous write','Other');
insert into waitgroups values ('change tracking file parallel write','Other');
insert into waitgroups values ('block change tracking buffer space','Other');
insert into waitgroups values ('enq: CT - global space management','Other');
insert into waitgroups values ('enq: CT - local space management','Other');
insert into waitgroups values ('enq: CT - change stream ownership','Other');
insert into waitgroups values ('enq: CT - state','Other');
insert into waitgroups values ('enq: CT - state change gate 1','Other');
insert into waitgroups values ('enq: CT - state change gate 2','Other');
insert into waitgroups values ('enq: CT - CTWR process start/stop','Other');
insert into waitgroups values ('enq: CT - reading','Other');
insert into waitgroups values ('recovery area: computing dropped files','Other');
insert into waitgroups values ('recovery area: computing obsolete files','Other');
insert into waitgroups values ('recovery area: computing identical files','Other');
insert into waitgroups values ('recovery area: computing backed up files','Other');
insert into waitgroups values ('recovery area: computing applied logs','Other');
insert into waitgroups values ('enq: RS - file delete','Other');
insert into waitgroups values ('enq: RS - record reuse','Other');
insert into waitgroups values ('enq: RS - prevent file delete','Other');
insert into waitgroups values ('enq: RS - prevent aging list update','Other');
insert into waitgroups values ('enq: RS - persist alert level','Other');
insert into waitgroups values ('enq: RS - read alert level','Other');
insert into waitgroups values ('enq: RS - write alert level','Other');
insert into waitgroups values ('enq: FL - Flashback database log','Other');
insert into waitgroups values ('enq: FL - Flashback db command','Other');
insert into waitgroups values ('enq: FD - Marker generation','Other');
insert into waitgroups values ('enq: FD - Tablespace flashback on/off','Other');
insert into waitgroups values ('enq: FD - Flashback coordinator','Other');
insert into waitgroups values ('enq: FD - Flashback on/off','Other');
insert into waitgroups values ('enq: FD - Restore point create/drop','Other');
insert into waitgroups values ('flashback free VI log','Other');
insert into waitgroups values ('flashback buf free by RVWR','Other');
insert into waitgroups values ('flashback log switch','Other');
insert into waitgroups values ('RVWR wait for flashback copy','Other');
insert into waitgroups values ('transaction','Other');
insert into waitgroups values ('inactive transaction branch','Other');
insert into waitgroups values ('txn to complete','Other');
insert into waitgroups values ('PMON to cleanup pseudo-branches at svc stop time','Other');
insert into waitgroups values ('test long ops','Other');
insert into waitgroups values ('enq: TF - contention','Other');
insert into waitgroups values ('Wait for shrink lock2','Other');
insert into waitgroups values ('Wait for shrink lock','Other');
insert into waitgroups values ('L1 validation','Other');
insert into waitgroups values ('Wait for TT enqueue','Other');
insert into waitgroups values ('kttm2d','Other');
insert into waitgroups values ('ktsambl','Other');
insert into waitgroups values ('ktfbtgex','Other');
insert into waitgroups values ('enq: DT - contention','Other');
insert into waitgroups values ('enq: TS - contention','Other');
insert into waitgroups values ('enq: FB - contention','Other');
insert into waitgroups values ('enq: SK - contention','Other');
insert into waitgroups values ('latch: undo global data','Other');
insert into waitgroups values ('undo segment recovery','Other');
insert into waitgroups values ('unbound tx','Other');
insert into waitgroups values ('wait for change','Other');
insert into waitgroups values ('wait for another txn - undo rcv abort','Other');
insert into waitgroups values ('wait for another txn - txn abort','Other');
insert into waitgroups values ('wait for another txn - rollback to savepoint','Other');
insert into waitgroups values ('undo_retention publish retry','Other');
insert into waitgroups values ('enq: TA - contention','Other');
insert into waitgroups values ('enq: TX - contention','Other');
insert into waitgroups values ('enq: US - contention','Other');
insert into waitgroups values ('enq: SU - contention','Other');
insert into waitgroups values ('enq: TT - contention','Other');
insert into waitgroups values ('ktm: instance recovery','Other');
insert into waitgroups values ('instance state change','Other');
insert into waitgroups values ('wait for stopper event to be increased','Other');
insert into waitgroups values ('wait for a undo record','Other');
insert into waitgroups values ('wait for a paralle reco to abort','Other');
insert into waitgroups values ('enq: IM - contention for blr','Other');
insert into waitgroups values ('enq: TD - KTF dump entries','Other');
insert into waitgroups values ('enq: TE - KTF broadcast','Other');
insert into waitgroups values ('enq: CN - race with txn','Other');
insert into waitgroups values ('enq: CN - race with reg','Other');
insert into waitgroups values ('enq: CN - race with init','Other');
insert into waitgroups values ('latch: Change Notification Hash table latch','Other');
insert into waitgroups values ('index block split','Other');
insert into waitgroups values ('enq: HV - contention','Other');
insert into waitgroups values ('dupl. cluster key','Other');
insert into waitgroups values ('kdic_do_merge','Other');
insert into waitgroups values ('enq: DL - contention','Other');
insert into waitgroups values ('enq: HQ - contention','Other');
insert into waitgroups values ('enq: HP - contention','Other');
insert into waitgroups values ('enq: DV - contention','Other');
insert into waitgroups values ('enq: RW - MV metadata contention','Other');
insert into waitgroups values ('enq: OC - contention','Other');
insert into waitgroups values ('enq: OL - contention','Other');
insert into waitgroups values ('kkdlgon','Other');
insert into waitgroups values ('kkdlsipon','Other');
insert into waitgroups values ('kkdlhpon','Other');
insert into waitgroups values ('kgltwait','Other');
insert into waitgroups values ('kksfbc research','Other');
insert into waitgroups values ('kksscl hash split','Other');
insert into waitgroups values ('kksfbc child completion','Other');
insert into waitgroups values ('enq: CU - contention','Other');
insert into waitgroups values ('cursor: pin X','Other');
insert into waitgroups values ('cursor: pin S','Other');
insert into waitgroups values ('enq: PF - contention','Other');
insert into waitgroups values ('enq: IL - contention','Other');
insert into waitgroups values ('enq: CL - drop label','Other');
insert into waitgroups values ('enq: CL - compare labels','Other');
insert into waitgroups values ('enq: MK - contention','Other');
insert into waitgroups values ('enq: OW - initialization','Other');
insert into waitgroups values ('enq: OW - termination','Other');
insert into waitgroups values ('enq: AU - audit index file','Other');
insert into waitgroups values ('enq: DX - contention','Other');
insert into waitgroups values ('enq: DR - contention','Other');
insert into waitgroups values ('pending global transaction(s)','Other');
insert into waitgroups values ('free global transaction table entry','Other');
insert into waitgroups values ('library cache revalidation','Other');
insert into waitgroups values ('library cache shutdown','Other');
insert into waitgroups values ('BFILE closure','Other');
insert into waitgroups values ('BFILE check if exists','Other');
insert into waitgroups values ('BFILE check if open','Other');
insert into waitgroups values ('BFILE get length','Other');
insert into waitgroups values ('BFILE get name object','Other');
insert into waitgroups values ('BFILE get path object','Other');
insert into waitgroups values ('BFILE open','Other');
insert into waitgroups values ('BFILE internal seek','Other');
insert into waitgroups values ('waiting to get CAS latch','Other');
insert into waitgroups values ('waiting to get RM CAS latch','Other');
insert into waitgroups values ('dispatcher shutdown','Other');
insert into waitgroups values ('latch: virtual circuit queues','Other');
insert into waitgroups values ('listen endpoint status','Other');
insert into waitgroups values ('select wait','Other');
insert into waitgroups values ('jobq slave shutdown wait','Other');
insert into waitgroups values ('jobq slave TJ process wait','Other');
insert into waitgroups values ('job scheduler coordinator slave wait','Other');
insert into waitgroups values ('enq: JD - contention','Other');
insert into waitgroups values ('enq: JQ - contention','Other');
insert into waitgroups values ('kkshgnc reloop','Other');
insert into waitgroups values ('optimizer stats update retry','Other');
insert into waitgroups values ('wait active processes','Other');
insert into waitgroups values ('enq: MD - contention','Other');
insert into waitgroups values ('enq: MS - contention','Other');
insert into waitgroups values ('PX slave connection','Other');
insert into waitgroups values ('PX slave release','Other');
insert into waitgroups values ('PX Send Wait','Other');
insert into waitgroups values ('PX qref latch','Other');
insert into waitgroups values ('PX server shutdown','Other');
insert into waitgroups values ('PX create server','Other');
insert into waitgroups values ('PX signal server','Other');
insert into waitgroups values ('PX Deq Credit: free buffer','Other');
insert into waitgroups values ('PX Deq Credit: send blkd','Other');
insert into waitgroups values ('PX Deq: Test for msg','Other');
insert into waitgroups values ('PX Deq: Signal ACK','Other');
insert into waitgroups values ('PX Deq: reap credit','Other');
insert into waitgroups values ('PX Nsq: PQ descriptor query','Other');
insert into waitgroups values ('PX Nsq: PQ load info query','Other');
insert into waitgroups values ('enq: PI - contention','Other');
insert into waitgroups values ('enq: PS - contention','Other');
insert into waitgroups values ('latch: parallel query alloc buffer','Other');
insert into waitgroups values ('kxfxse','Other');
insert into waitgroups values ('kxfxsp','Other');
insert into waitgroups values ('PX Deq: Table Q qref','Other');
insert into waitgroups values ('PX Deq: Table Q Get Keys','Other');
insert into waitgroups values ('PX Deq: Table Q Close','Other');
insert into waitgroups values ('GV$: slave acquisition retry wait time','Other');
insert into waitgroups values ('enq: TO - contention','Other');
insert into waitgroups values ('enq: IT - contention','Other');
insert into waitgroups values ('enq: BF - allocation contention','Other');
insert into waitgroups values ('timer in sksawat','Other');
insert into waitgroups values ('scginq AST call','Other');
insert into waitgroups values ('kupp process wait','Other');
insert into waitgroups values ('Kupp process shutdown','Other');
insert into waitgroups values ('enq: KP - contention','Other');
insert into waitgroups values ('Replication Dequeue ','Other');
insert into waitgroups values ('knpc_acwm_AwaitChangedWaterMark','Other');
insert into waitgroups values ('knpc_anq_AwaitNonemptyQueue','Other');
insert into waitgroups values ('knpsmai','Other');
insert into waitgroups values ('enq: SR - contention','Other');
insert into waitgroups values ('Streams capture: waiting for database startup','Other');
insert into waitgroups values ('Streams capture: waiting for archive log','Other');
insert into waitgroups values ('enq: SI - contention','Other');
insert into waitgroups values ('enq: IA - contention','Other');
insert into waitgroups values ('enq: JI - contention','Other');
insert into waitgroups values ('qerex_gdml','Other');
insert into waitgroups values ('enq: AT - contention','Other');
insert into waitgroups values ('opishd','Other');
insert into waitgroups values ('wait for EMON to spawn','Other');
insert into waitgroups values ('wait for EMON to die','Other');
insert into waitgroups values ('enq: SE - contention','Other');
insert into waitgroups values ('tsm with timeout','Other');
insert into waitgroups values ('Streams AQ: waiting for busy instance for instance_name','Other');
insert into waitgroups values ('enq: TQ - TM contention','Other');
insert into waitgroups values ('enq: TQ - DDL contention','Other');
insert into waitgroups values ('enq: TQ - INI contention','Other');
insert into waitgroups values ('enq: DP - contention','Other');
insert into waitgroups values ('enq: MH - contention','Other');
insert into waitgroups values ('enq: ML - contention','Other');
insert into waitgroups values ('enq: PH - contention','Other');
insert into waitgroups values ('enq: SF - contention','Other');
insert into waitgroups values ('enq: XH - contention','Other');
insert into waitgroups values ('enq: WA - contention','Other');
insert into waitgroups values ('Streams AQ: enqueue blocked due to flow control','Other');
insert into waitgroups values ('queue slave messages','Other');
insert into waitgroups values ('Streams AQ: qmn coordinator waiting for slave to start','Other');
insert into waitgroups values ('rfm_dmon_pdefer','Other');
insert into waitgroups values ('rfm_dmon_shut','Other');
insert into waitgroups values ('rfm_dmon_timeout_op','Other');
insert into waitgroups values ('rfm_pmon_dso_stall','Other');
insert into waitgroups values ('rfm_dmon_last_gasp','Other');
insert into waitgroups values ('Data Guard broker: single instance','Other');
insert into waitgroups values ('rfrm_dbop','Other');
insert into waitgroups values ('rfrm_dbcl','Other');
insert into waitgroups values ('rfrm_stall','Other');
insert into waitgroups values ('rfrm_rsm_shut','Other');
insert into waitgroups values ('rfrm_zero_sub_count','Other');
insert into waitgroups values ('rfrm_rsm_start','Other');
insert into waitgroups values ('rfrm_nonzero_sub_count','Other');
insert into waitgroups values ('rfrm_rsm_so_attach','Other');
insert into waitgroups values ('rfi_drcx_site_del','Other');
insert into waitgroups values ('rfi_insv_shut','Other');
insert into waitgroups values ('rfi_insv_start','Other');
insert into waitgroups values ('rfi_nsv_deldef','Other');
insert into waitgroups values ('rfi_nsv_md_close','Other');
insert into waitgroups values ('rfi_nsv_md_write','Other');
insert into waitgroups values ('rfi_nsv_postdef','Other');
insert into waitgroups values ('rfi_nsv_shut','Other');
insert into waitgroups values ('rfi_nsv_start','Other');
insert into waitgroups values ('rfi_recon1','Other');
insert into waitgroups values ('rfi_recon2','Other');
insert into waitgroups values ('enq: RF - synch: DG Broker metadata','Other');
insert into waitgroups values ('enq: RF - atomicity','Other');
insert into waitgroups values ('enq: RF - synchronization: chief','Other');
insert into waitgroups values ('enq: RF - synchronization: HC master','Other');
insert into waitgroups values ('enq: RF - synchronization: aifo master','Other');
insert into waitgroups values ('enq: RF - new AI','Other');
insert into waitgroups values ('enq: RF - synchronization: critical ai','Other');
insert into waitgroups values ('enq: RF - RF - FSFO state','Other');
insert into waitgroups values ('enq: RF - RF - FSFO wait','Other');
insert into waitgroups values ('enq: RF - RF - FSFO connectivity','Other');
insert into waitgroups values ('enq: RF - RF - FSFO synchronization','Other');
insert into waitgroups values ('enq: RF - RF - FSFO Observed','Other');
insert into waitgroups values ('rfrxptarcurlog','Other');
insert into waitgroups values ('rfrxpt_pdl','Other');
insert into waitgroups values ('rfrdb_recon1','Other');
insert into waitgroups values ('rfrdb_recon2','Other');
insert into waitgroups values ('rfrdb_dbop','Other');
insert into waitgroups values ('rfrdb_try235','Other');
insert into waitgroups values ('Data Guard broker: wait upon ORA-12850 error','Other');
insert into waitgroups values ('rfrla_lapp1','Other');
insert into waitgroups values ('rfrla_lapp2','Other');
insert into waitgroups values ('rfrla_lapp3','Other');
insert into waitgroups values ('rfrla_lapp4','Other');
insert into waitgroups values ('rfrla_lapp5','Other');
insert into waitgroups values ('rfrpa_mrpup','Other');
insert into waitgroups values ('rfrpa_mrpdn','Other');
insert into waitgroups values ('RF - FSFO Wait for Ack','Other');
insert into waitgroups values ('rfrld_rhmrpwait','Other');
insert into waitgroups values ('PX Deq: OLAP Update Reply','Other');
insert into waitgroups values ('PX Deq: OLAP Update Execute','Other');
insert into waitgroups values ('PX Deq: OLAP Update Close','Other');
insert into waitgroups values ('OLAP Parallel Type Deq','Other');
insert into waitgroups values ('OLAP Parallel Temp Grow Request','Other');
insert into waitgroups values ('OLAP Parallel Temp Grow Wait','Other');
insert into waitgroups values ('OLAP Parallel Temp Grew','Other');
insert into waitgroups values ('OLAP Null PQ Reason','Other');
insert into waitgroups values ('OLAP Aggregate Master Enq','Other');
insert into waitgroups values ('OLAP Aggregate Client Enq','Other');
insert into waitgroups values ('OLAP Aggregate Master Deq','Other');
insert into waitgroups values ('OLAP Aggregate Client Deq','Other');
insert into waitgroups values ('enq: AW - AW$ table lock','Other');
insert into waitgroups values ('enq: AW - AW state lock','Other');
insert into waitgroups values ('enq: AW - user access for AW','Other');
insert into waitgroups values ('enq: AW - AW generation lock','Other');
insert into waitgroups values ('enq: AG - contention','Other');
insert into waitgroups values ('enq: AO - contention','Other');
insert into waitgroups values ('enq: OQ - xsoqhiAlloc','Other');
insert into waitgroups values ('enq: OQ - xsoqhiFlush','Other');
insert into waitgroups values ('enq: OQ - xsoq*histrecb','Other');
insert into waitgroups values ('enq: OQ - xsoqhiClose','Other');
insert into waitgroups values ('enq: OQ - xsoqhistrecb','Other');
insert into waitgroups values ('enq: AM - client registration','Other');
insert into waitgroups values ('enq: AM - shutdown','Other');
insert into waitgroups values ('enq: AM - rollback COD reservation','Other');
insert into waitgroups values ('ASM internal hang test','Other');
insert into waitgroups values ('buffer busy','Other');
insert into waitgroups values ('buffer freelistbusy','Other');
insert into waitgroups values ('buffer rememberlist busy','Other');
insert into waitgroups values ('buffer writeList full','Other');
insert into waitgroups values ('no free buffers','Other');
insert into waitgroups values ('buffer write wait','Other');
insert into waitgroups values ('buffer invalidation wait','Other');
insert into waitgroups values ('buffer dirty disabled','Other');
insert into waitgroups values ('enq: CM - gate','Other');
insert into waitgroups values ('enq: CM - instance','Other');
insert into waitgroups values ('enq: XQ - recovery','Other');
insert into waitgroups values ('enq: XQ - relocation','Other');
insert into waitgroups values ('enq: AD - allocate AU','Other');
insert into waitgroups values ('enq: AD - deallocate AU','Other');
insert into waitgroups values ('extent map load/unlock','Other');
insert into waitgroups values ('Sync ASM rebalance','Other');
insert into waitgroups values ('enq: DG - contention','Other');
insert into waitgroups values ('enq: DD - contention','Other');
insert into waitgroups values ('enq: HD - contention','Other');
insert into waitgroups values ('enq: DN - contention','Other');
insert into waitgroups values ('Cluster stablization wait','Other');
insert into waitgroups values ('Cluster Suspension wait','Other');
insert into waitgroups values ('ASM background starting','Other');
insert into waitgroups values ('ASM background running','Other');
insert into waitgroups values ('ASM db client exists','Other');
insert into waitgroups values ('DBFG waiting for reply','Other');
insert into waitgroups values ('enq: FA - access file','Other');
insert into waitgroups values ('log write(odd)','Other');
insert into waitgroups values ('log write(even)','Other');
insert into waitgroups values ('checkpoint advanced','Other');
insert into waitgroups values ('enq: FR - contention','Other');
insert into waitgroups values ('enq: FG - serialize ACD relocate','Other');
insert into waitgroups values ('enq: FG - FG redo generation enq race','Other');
insert into waitgroups values ('enq: FG - LGWR redo generation enq race','Other');
insert into waitgroups values ('enq: FT - allow LGWR writes','Other');
insert into waitgroups values ('enq: FT - disable LGWR writes','Other');
insert into waitgroups values ('enq: FC - open an ACD thread','Other');
insert into waitgroups values ('enq: FC - recover an ACD thread','Other');
insert into waitgroups values ('rollback operations block full','Other');
insert into waitgroups values ('rollback operations active','Other');
insert into waitgroups values ('enq: RB - contention','Other');
insert into waitgroups values ('enq: PT - contention','Other');
insert into waitgroups values ('global cache busy','Other');
insert into waitgroups values ('lock release pending','Other');
insert into waitgroups values ('dma prepare busy','Other');
insert into waitgroups values ('GCS lock cancel','Other');
insert into waitgroups values ('GCS lock open S','Other');
insert into waitgroups values ('GCS lock open X','Other');
insert into waitgroups values ('GCS lock open','Other');
insert into waitgroups values ('GCS lock cvt S','Other');
insert into waitgroups values ('GCS lock cvt X','Other');
insert into waitgroups values ('GCS lock esc X','Other');
insert into waitgroups values ('GCS lock esc','Other');
insert into waitgroups values ('GCS recovery lock open','Other');
insert into waitgroups values ('GCS recovery lock convert','Other');
insert into waitgroups values ('kfcl: instance recovery','Other');
insert into waitgroups values ('no free locks','Other');
insert into waitgroups values ('lock close','Other');
insert into waitgroups values ('enq: WF - contention','Other');
insert into waitgroups values ('enq: WP - contention','Other');
insert into waitgroups values ('enq: FU - contention','Other');
insert into waitgroups values ('enq: MW - contention','Other');
insert into waitgroups values ('AWR Flush','Other');
insert into waitgroups values ('AWR Metric Capture','Other');
insert into waitgroups values ('enq: TB - SQL Tuning Base Cache Update','Other');
insert into waitgroups values ('enq: TB - SQL Tuning Base Cache Load','Other');
insert into waitgroups values ('enq: SH - contention','Other');
insert into waitgroups values ('enq: AF - task serialization','Other');
insert into waitgroups values ('MMON slave messages','Other');
insert into waitgroups values ('MMON (Lite) shutdown','Other');
insert into waitgroups values ('enq: TL - contention','Other');
insert into waitgroups values ('enq: JS - contention','Other');
insert into waitgroups values ('enq: JS - job run lock - synchronize','Other');
insert into waitgroups values ('enq: JS - job recov lock','Other');
insert into waitgroups values ('enq: JS - queue lock','Other');
insert into waitgroups values ('enq: JS - sch locl enqs','Other');
insert into waitgroups values ('enq: JS - q mem clnup lck','Other');
insert into waitgroups values ('enq: JS - evtsub add','Other');
insert into waitgroups values ('enq: JS - evtsub drop','Other');
insert into waitgroups values ('enq: JS - wdw op','Other');
insert into waitgroups values ('enq: JS - evt notify','Other');
insert into waitgroups values ('secondary event','Other');

-- 9 waits
insert into waitgroups values ('unspecified event','Other');
insert into waitgroups values ('name service busy','Other');
insert into waitgroups values ('ksimret is busy in recovery','Other');
insert into waitgroups values ('background parameter adjustment','Other');
insert into waitgroups values ('enqueue','Application');
insert into waitgroups values ('trace writer flush','Other');
insert into waitgroups values ('trace writer I/O','Other');
insert into waitgroups values ('trace unfreeze','Other');
insert into waitgroups values ('trace continue','Other');
insert into waitgroups values ('async disk IO','Other');
insert into waitgroups values ('fib/fob latch','Other');
insert into waitgroups values ('sbtinit','Other');
insert into waitgroups values ('sbtopen','Other');
insert into waitgroups values ('sbtread','Other');
insert into waitgroups values ('sbtwrite','Other');
insert into waitgroups values ('sbtclose','Other');
insert into waitgroups values ('sbtinfo','Other');
insert into waitgroups values ('sbtremove','Other');
insert into waitgroups values ('sbtbackup','Other');
insert into waitgroups values ('sbtclose2','Other');
insert into waitgroups values ('sbtcommand','Other');
insert into waitgroups values ('sbtend','Other');
insert into waitgroups values ('sbterror','Other');
insert into waitgroups values ('sbtinfo2','Other');
insert into waitgroups values ('sbtinit2','Other');
insert into waitgroups values ('sbtread2','Other');
insert into waitgroups values ('sbtremove2','Other');
insert into waitgroups values ('sbtrestore','Other');
insert into waitgroups values ('sbtwrite2','Other');
insert into waitgroups values ('sbtpcbackup','Other');
insert into waitgroups values ('sbtpccancel','Other');
insert into waitgroups values ('sbtpccommit','Other');
insert into waitgroups values ('sbtpcend','Other');
insert into waitgroups values ('sbtpcquerybackup','Other');
insert into waitgroups values ('sbtpcqueryrestore','Other');
insert into waitgroups values ('sbtpcrestore','Other');
insert into waitgroups values ('sbtpcstart','Other');
insert into waitgroups values ('sbtpcstatus','Other');
insert into waitgroups values ('sbtpcvalidate','Other');
insert into waitgroups values ('DIAG dummy wait','Other');
insert into waitgroups values ('ges global resource directory to be unfrozen','Other');
insert into waitgroups values ('wait for scn from all nodes','Other');
insert into waitgroups values ('ges cgs de-registration','Other');
insert into waitgroups values ('ges server qs to be empty - kjbrrit','Other');
insert into waitgroups values ('ges proc table latch - kjdrptref','Other');
insert into waitgroups values ('ges lmd/lmses to freeze in rcfg - srcvr','Other');
insert into waitgroups values ('ges lmd/lmses to unfreeze in rcfg - srcvr','Other');
insert into waitgroups values ('ges process allocation','Other');
insert into waitgroups values ('ges drm deferred close','Other');
insert into waitgroups values ('ges drm freeze begin','Other');
insert into waitgroups values ('ges1 LMON to wake up LMD','Other');
insert into waitgroups values ('ges2 LMON to wake up LMD - srcvr','Other');
insert into waitgroups values ('ges LMON for send buffers to be empty','Other');
insert into waitgroups values ('ges LMS suspend for testing event','Other');
insert into waitgroups values ('wait for membership change','Other');
insert into waitgroups values ('gcs for action','Other');
insert into waitgroups values ('contacting SCN server or SCN lock master','Other');
insert into waitgroups values ('refresh controlfile command','Other');
insert into waitgroups values ('buffer busy global cache','Other');
insert into waitgroups values ('buffer busy global CR','Other');
insert into waitgroups values ('cache simulator heap','Other');
insert into waitgroups values ('conversion file read','Other');
insert into waitgroups values ('global cache open s','Other');
insert into waitgroups values ('global cache open x','Other');
insert into waitgroups values ('global cache null to s','Other');
insert into waitgroups values ('global cache null to x','Other');
insert into waitgroups values ('global cache s to x','Other');
insert into waitgroups values ('global cache cr request','Other');
insert into waitgroups values ('global cache cr disk request','Other');
insert into waitgroups values ('global cache freelist wait','Other');
insert into waitgroups values ('global cache bg acks','Other');
insert into waitgroups values ('global cache pending ast','Other');
insert into waitgroups values ('global cache retry prepare','Other');
insert into waitgroups values ('global cache cancel wait','Other');
insert into waitgroups values ('global cache cr cancel wait','Other');
insert into waitgroups values ('global cache pred cancel wait','Other');
insert into waitgroups values ('global cache domain validation','Other');
insert into waitgroups values ('global cache assume wait','Other');
insert into waitgroups values ('global cache recovery free wait','Other');
insert into waitgroups values ('global cache recovery quiesce wait','Other');
insert into waitgroups values ('global cache claim wait','Other');
insert into waitgroups values ('global cache remastering wait','Other');
insert into waitgroups values ('global cache quiesce wait','Other');
insert into waitgroups values ('direct path read (lob) ','Other');
insert into waitgroups values ('direct path write (lob)','Other');
insert into waitgroups values ('wait for activate message','Other');
insert into waitgroups values ('wakeup event for builder','Other');
insert into waitgroups values ('wakeup event for preparer','Other');
insert into waitgroups values ('wakeup event for reader','Other');
insert into waitgroups values ('wait for transaction','Other');
insert into waitgroups values ('wait for Logical Standby Apply shutdown','Other');
insert into waitgroups values ('Wait for Dictionary Build to lock all tables','Other');
insert into waitgroups values ('instance recovery','Other');
insert into waitgroups values ('file identify','Other');
insert into waitgroups values ('file open','Other');
insert into waitgroups values ('resmgr:wait in actses run','Other');
insert into waitgroups values ('resmgr:waiting in end wait','Other');
insert into waitgroups values ('resmgr:waiting in check','Other');
insert into waitgroups values ('resmgr:waiting in system stop','Other');
insert into waitgroups values ('resmgr:waiting in enter','Other');
insert into waitgroups values ('resmgr:waiting in shutdown','Other');
insert into waitgroups values ('resmgr:waiting in check2','Other');
insert into waitgroups values ('resmgr:waiting in enter2','Other');
insert into waitgroups values ('resmgr:waiting in run (queued)','Other');
insert into waitgroups values ('resmgr:waiting in end wait2','Other');
insert into waitgroups values ('resmgr:waiting for cschlat1','Other');
insert into waitgroups values ('resmgr:waiting for cschlat2','Other');
insert into waitgroups values ('resmgr:waiting for cschlat3','Other');
insert into waitgroups values ('resmgr:waiting for cschlat4','Other');
insert into waitgroups values ('slave shutdown wait','Other');
insert into waitgroups values ('slave TJ process wait','Other');
insert into waitgroups values ('qxdid_gdml','Other');
insert into waitgroups values ('queue messages','Other');
insert into waitgroups values ('wakeup time manager','Other');
insert into waitgroups values ('STREAMS apply coord waiting for slave message','Other');
insert into waitgroups values ('STREAMS apply coord waiting for some work to finish','Other');
insert into waitgroups values ('STREAMS fetch slave waiting for txns','Other');
insert into waitgroups values ('STREAMS apply slave waiting for coord message','Other');
insert into waitgroups values ('knlWaitForStartup','Other');
insert into waitgroups values ('STREAMS capture process waiting for archive log','Other');
insert into waitgroups values ('STREAMS capture process filter callback wait for ruleset','Other');
insert into waitgroups values ('Streams: Wating for DDL to apply','Other');
insert into waitgroups values ('knlqdeq','Other');

update  sash_event_names sen 
   set sen.wait_class = ( select wg.wait_class from
       waitgroups wg where wg.name=sen.name);

commit;